# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'Image.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.



from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QLabel, QFileDialog
from PyQt5 import uic
from PyQt5.QtGui import QPixmap
import sys


class Ui_MainWindow(QMainWindow):


    def __init__(self):
        super(Ui_MainWindow,self).__init__()

        uic.loadUi("Image.ui",self)

        self.openfilebutton = self.findChild(QPushButton,"pushButton")
        self.label = self.findChild(QLabel,"label")

        self.openfilebutton.clicked.connect(self.clicker)


        self.button_rotate = self.findChild(QPushButton,"rotate")
        self.button_rotate.clicked.connect(self.rotate)
        self.show()

    def clicker(self):
        fname = QFileDialog.getOpenFileName(self, "Open File", "./images","All Files (*);;PNG Files (*.png);;Jpg Files(*.jpg)")
        # Open the image

        self.pixmap = QPixmap(fname[0])
        # add pic to label
        self.label.setPixmap(self.pixmap)

    def rotate(self):
        print("Rotating")

    # Initialize The App
app = QApplication(sys.argv)
UIWindow = Ui_MainWindow()
app.exec_()




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())


# from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QLabel, QFileDialog
# from PyQt5 import uic
# from PyQt5.QtGui import QPixmap
# import sys

# class UI(QMainWindow):
#     # def __init__(self):
#     def __init__(self):
# 	    super(UI, self).__init__()

# 		# Load the ui file
# 	    uic.loadUi("image.ui", self)

# 		# Define our widgets
# 	    self.button1 = self.findChild(QPushButton, "pushButton")
# 		self.label = self.findChild(QLabel, "label")

# 		# Click The Dropdown Box
# 		self.button1.clicked.connect(self.clicker)
#         self.button_rotate = self.findChild(QPushButton, "rotate")
#         self.button_rotate.clicked.connect(self.rotate)
						
# 		# Show The App
# 		self.show()

# 	def clicker(self):
# 		fname = QFileDialog.getOpenFileName(self, "Open File", ".\images", "All Files (*);;PNG Files (*.png);;Jpg Files (*.jpg)") 

# 		# Open The Image
# 		if fname:
# 			self.pixmap = QPixmap(fname[0])
# 			# Add Pic to label
# 			self.label.setPixmap(self.pixmap)
    
#     # def rotate(self):
#     #     print("Rotate")

# # Initialize The App
# app = QApplication(sys.argv)
# UIWindow = UI()
# app.exec_()
